# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: parallax
# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-finch

custom:
  client:
    bucketName: parallax-page # (see Configuration Parameters below)
    distributionFolder: web
    indexDocument: index.html
    errorDocument: index.html
